project:
  type: website
  output-dir: _site

website:
  title: "Life Expectancy Gender Gap Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tech_report.qmd
        text: Technical Report
      - href: bayesian_model_r.ipynb
        text: R Model Notebook

